words = ("apple", "river", "mountain", "teacher", "computer", "school", "book", "idea", "dream", "city",
"car", "phone", "house", "friend", "music", "forest", "dog", "cat", "rain", "sun",
"cloud", "tree", "flower", "bird", "desk", "chair", "window", "door", "lake", "road",
"village", "family", "brother", "sister", "mother", "father", "student", "pen", "pencil", "paper",
"clock", "camera", "movie", "garden", "hotel", "restaurant", "riverbank", "island", "bridge", "sky",
"planet", "moon", "star", "ocean", "wave", "ship", "boat", "train", "station", "airport",
"ticket", "bag", "key", "wallet", "mirror", "shirt", "shoe", "jacket", "hat", "watch",
"game", "ball", "goal", "player", "team", "coach", "stadium", "match", "winner", "trophy",
"money", "bank", "coin", "note", "shop", "market", "price", "customer", "seller", "product",
"language", "sentence", "word", "letter", "voice", "sound", "image", "picture", "painting", "art",
"science", "history", "math", "physics", "chemistry", "biology", "experiment", "test", "result", "data",
"student", "teacher", "class", "lesson", "subject", "exam", "library", "notebook", "folder", "document",
"street", "park", "building", "hospital", "office", "factory", "museum", "theater", "bridge", "tower",
"mountain", "valley", "river", "sea", "beach", "sand", "stone", "rock", "hill", "cave",
"freedom", "happiness", "success", "failure", "truth", "hope", "power", "peace", "love", "future") 